'use strict';

/**
 * In-flight BYOK AI request tracker.
 *
 * Pure-JS module — no Electron or filesystem dependency.  Each request tracked
 * here includes an AbortController so the user (or a timeout/cleanup sweep) can
 * cancel it without leaking resources.
 *
 * The store is a module-level Map keyed by request ID.  Request IDs are opaque
 * strings generated by the caller (typically a UUID or counter).
 */

/**
 * Internal per-request record.
 * @typedef {object} RequestEntry
 * @property {AbortController} abortController
 * @property {'pending'|'streaming'|'completed'|'aborted'|'errored'} status
 * @property {number}  startTime  — Date.now() when the request was created
 * @property {Error|null} error   — set when status === 'errored'
 */

/** @type {Map<string,RequestEntry>} */
const _requests = new Map();

/**
 * Register a new in-flight request.
 *
 * @param {string} requestId  Unique identifier for this request.
 * @returns {RequestEntry} The newly created entry.
 */
function createRequest(requestId) {
  if (_requests.has(requestId)) {
    throw new Error(`Request "${requestId}" already exists`);
  }
  const entry = {
    abortController: new AbortController(),
    status: 'pending',
    startTime: Date.now(),
    error: null,
  };
  _requests.set(requestId, entry);
  return entry;
}

/**
 * Look up a tracked request by ID.
 *
 * @param {string} requestId
 * @returns {RequestEntry|undefined}
 */
function getRequest(requestId) {
  return _requests.get(requestId);
}

/**
 * Abort an in-flight request (calls AbortController.abort() and updates status).
 *
 * @param {string} requestId
 * @returns {boolean} true if the request was found and aborted, false if not found.
 */
function abortRequest(requestId) {
  const entry = _requests.get(requestId);
  if (!entry) return false;
  entry.abortController.abort();
  entry.status = 'aborted';
  return true;
}

/**
 * Remove a request from the store after it has completed.
 *
 * @param {string} requestId
 * @returns {boolean} true if the request was found and removed.
 */
function cleanupRequest(requestId) {
  return _requests.delete(requestId);
}

/**
 * Return a snapshot of all active (non-completed, non-aborted) requests.
 *
 * @returns {Array<{id: string, status: string, startTime: number}>}
 */
function getActiveRequests() {
  const active = [];
  for (const [id, entry] of _requests) {
    if (entry.status === 'pending' || entry.status === 'streaming') {
      active.push({
        id,
        status: entry.status,
        startTime: entry.startTime,
      });
    }
  }
  return active;
}

/**
 * Return the raw count of tracked entries (for diagnostics / test assertions).
 * @returns {number}
 */
function _size() {
  return _requests.size;
}

/**
 * Remove all entries (for test teardown).
 */
function _reset() {
  _requests.clear();
}

module.exports = {
  createRequest,
  getRequest,
  abortRequest,
  cleanupRequest,
  getActiveRequests,
  _size,
  _reset,
};
